-- This is dispensation data from 3 pharmacy facilities managed by the Ghana ecommerce department.

use portfolioproject;
select 	* from 	ecommerce;
alter table ecommerce add column date date;
alter table ecommerce modify column	date date after	sale_date;
update 	ecommerce set date = left(sale_date,10);

-- *-----------------------------------------------------------------------

-- 1. Total revenue generated (FY)
select round(sum(sale_item_selling_price_local),2) as FY_Revenue from ecommerce;

-- 2. Total revenue generated by Month
select date_format(date, '%M') as month, round(sum(sale_item_selling_price_local),2) as Revenue 
from ecommerce
group by 1, month(date)
order by month(date);

-- 3. Revenue distribution by facility.
with cte as (
select round(sum(sale_item_selling_price_local),2) as FY_Revenue from ecommerce
)
select 
	sale_facility, 
    round(sum(sale_item_selling_price_local),2) as Revenue, 
    round((sum(sale_item_selling_price_local)/cte.FY_Revenue)*100,2) as Revenue_Percentage
from ecommerce, cte
group by sale_facility, cte.FY_revenue;

-- 4. Revenue distribution by insurance Payor
with cte as (
select round(sum(sale_item_selling_price_local),2) as FY_Revenue from ecommerce
)
select
	insurance_payor,
    round(sum(sale_item_selling_price_local),2) as Revenue,
    round((sum(sale_item_selling_price_local)/cte.FY_Revenue)*100,2) as Revenue_Percentage
from ecommerce, cte
where insurance_payor not in ('None','')
group by 1,cte.FY_Revenue;

-- 5. Top Products by Value Sold
select
	vdl_drug_display_name,
    round(sum(sale_item_selling_price_local),2) as Revenue
from ecommerce
group by 1 order by 2 desc;

-- 5. Top Products by Quantity Sold
select
	quantity_in_units,
    round(sum(sale_item_selling_price_local),2) as Revenue
from ecommerce
group by 1 order by 2 desc;
